title = "josh hogg"
baseURL = 'https://joshuahogg.github.io'

# This is what goes in <html lang="">
languageCode = 'en-us'

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] 

# theme component resides in directory 'themes'
theme = "hugo-blog-awesome"

[services]
  [services.googleAnalytics]
    id = '' 
  [services.disqus]
    shortname = ''

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2 
    endLevel = 4 
    ordered = false 

############################## English language ################################
[Languages.en-gb]
  languageName = "English"
  languageCode = "en-gb"
  contentDir = "content/en"
  weight = 1

  [Languages.en-gb.menu]
  [[Languages.en-gb.menu.main]]
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-gb.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.en-gb.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[Languages.en-gb.params]
  sitename = "josh hogg"
  defaultColor = "dark" # dark, light, auto
  description = "An ongoing examination of culture, technology and media."
  mainSections = ['posts']
  toc = true 
  tocOpen = false 
  goToTop = true 
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  dateFormat = "2 Jan 2006" 
  rssFeedDescription = "summary" 

[Languages.en-gb.params.author]
  avatar = "avatar.jpg" 
  intro = "Josh Hogg"
  name = "Josh Hogg"
  description = "An ongoing examination of culture, technology and media. Optimism tempered with a healthy dose of paranoia."

[Languages.en-gb.params.webmanifest]
  name = "josh hogg"
  short_name = "joshhogg"
  start_url = "/"
  theme_color = "#434648"
  background_color = "#fff"
  display = "standalone"

###################################################################

[params.browserconfig]
  TileColor = "#2d89ef" 

[[params.socialIcons]]
name = "github"
url = "https://github.com/joshuahogg"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"
